### ISSUE TITLE
Error handler: incorrect bitwise comparison

### ISSUE THREAD

**Issue by strarsis** [roots/acorn#100]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Note: `acorn` put the code of a previously deprecated package (on packagist) into its own repo.

There is a bug with the bitwise operation used in the condition to check for `error_reporting` as it doesn't work for disabled error_reporting or `error_reporting` without lower reporting levels:
https://github.com/roots/acorn/blob/a2ef0a5fe7a4b4d692838529a1b67c48245f0cbd/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L68

with `error_reporting` set to `0` or `E_ERROR | E_WARNING | E_PARSE` in order to skip `E_NOTICE` PHP errors, 
the error will still be thrown, shown and destroy the page markup at that point with injected "rich" error HTML.

## Steps to reproduce

1. Configure for lower or none `error_reporting`, e.g. for staging in `config/environments/staging.php`
2. Trigger a PHP `E_NOTICE` message, e.g. an `Undefined index` error by accessing an undefined index of a PHP array:
Note that these lower level PHP errors still cause a "rich" HTML error message, which shouldn't happen.

**Expected behavior:**
PHP errors with levels to be ignored.

**Actual behavior:**
PHP errors with levels to be ignored are still thrown.

**Reproduces how often:**
Always.

## Versions
Bedrock:
````
### 1.15.3: 2021-03-12
* chore(deps): Bump roots/wordpress from 5.6.2 to 5.7 ([#578](https://github.com/roots/bedrock/pull/578))
````

## Additional information
Related: https://github.com/roots/acorn/issues/87

**Comment by QWp6t** [comment]
This is intentional.

By default, deprecation errors won't throw exceptions, but every other type of error will.

If you want to suppress throwing `ErrorException`, use the [`acorn/throw_error_exception` filter](https://github.com/roots/acorn/blob/next/src/Roots/Acorn/Bootstrap/HandleExceptions.php#L54) on the `next` branch.
```php
add_filter('acorn/throw_error_exception', '__return_false');
```

We will be tagging another beta release shortly. In the meantime, feel free to switch to the `next` branch.
```sh
composer require roots/acorn dev-next
```
