### ISSUE TITLE
After updating Illuminate packages to 8.37 version application is broked

### ISSUE THREAD

**Issue by Besmerch123** [roots/acorn#102]
I`m updated my packages with `composer update` command, as usualy. 
And after yhat - whole application is broked. 
Everything worked fine before updating packages. 

Here is the most recent stacktrace: https://prnt.sc/11plccz

`ErrorException thrown with message "Undefined index: url"

Stacktrace:
#24 ErrorException in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Roots/Acorn/Assets/Manager.php:87
#23 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Roots/Acorn/Assets/Manager.php:87
#22 Roots\Acorn\Assets\Manager:resolve in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Roots/Acorn/Assets/Manager.php:66
#21 Roots\Acorn\Assets\Manager:manifest in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Roots/Acorn/Assets/AssetsServiceProvider.php:22
#20 Roots\Acorn\Assets\AssetsServiceProvider:Roots\Acorn\Assets\{closure} in /var/www/html/web/app/themes/zcci-theme/vendor/illuminate/container/Container.php:829
#19 Illuminate\Container\Container:build in /var/www/html/web/app/themes/zcci-theme/vendor/illuminate/container/Container.php:714
#18 Illuminate\Container\Container:resolve in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Illuminate/Foundation/Application.php:841
#17 Illuminate\Foundation\Application:resolve in /var/www/html/web/app/themes/zcci-theme/vendor/illuminate/container/Container.php:652
#16 Illuminate\Container\Container:make in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Illuminate/Foundation/Application.php:826
#15 Illuminate\Foundation\Application:make in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/Roots/Acorn/Application.php:304
#14 Roots\Acorn\Application:make in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/helpers.php:42
#13 Roots\app in /var/www/html/web/app/themes/zcci-theme/vendor/roots/acorn/src/helpers.php:67
#12 Roots\asset in /var/www/html/web/app/themes/zcci-theme/app/setup.php:21
#11 App\{closure} in /var/www/html/web/wp/wp-includes/class-wp-hook.php:292
#10 WP_Hook:apply_filters in /var/www/html/web/wp/wp-includes/class-wp-hook.php:316
#9 WP_Hook:do_action in /var/www/html/web/wp/wp-includes/plugin.php:484
#8 do_action in /var/www/html/web/wp/wp-includes/script-loader.php:2027
#7 wp_enqueue_scripts in /var/www/html/web/wp/wp-includes/class-wp-hook.php:292
#6 WP_Hook:apply_filters in /var/www/html/web/wp/wp-includes/class-wp-hook.php:316
#5 WP_Hook:do_action in /var/www/html/web/wp/wp-includes/plugin.php:484
#4 do_action in /var/www/html/web/wp/wp-includes/general-template.php:3009
#3 wp_head in /var/www/html/web/app/themes/zcci-theme/index.php:7
#2 include in /var/www/html/web/wp/wp-includes/template-loader.php:106
#1 require_once in /var/www/html/web/wp/wp-blog-header.php:19
#0 require in /var/www/html/web/index.php:6
`

**Comment by Besmerch123** [comment]
I`m updated php version to 8.0.3 - still broken.

**Comment by alevgal** [comment]
@Besmerch123 Hi, I have the same issue, did You solve it?

**Comment by Besmerch123** [comment]
@alevgal Yeah) The problem was in the "config" folder.  
There were many issues, I don't remember all of them. But I just created a fresh Sage 10 theme with composer, and compared file by file all "config" folder. 

what I remember... Definitely, the problem was here https://prnt.sc/12f83wg . 
This works without that line https://prnt.sc/12f84te . 

And some other changes in other files in the "config" folder.

**Comment by slackday** [comment]
@alevgal copy paste from https://raw.githubusercontent.com/roots/sage/master/config/assets.php

Edit `config/assets.php`Add and add `use function Roots\public_path;` to the top of the file.

Change

```
    'manifests' => [
        'theme' => [
            'strategy' => 'relative',
            'path' => get_theme_file_path('/public'),
            'uri' => get_theme_file_uri('/public'),
            'manifest' => get_theme_file_path('/public/mix-manifest.json'),
        ]
    ]
```

to

```
    'manifests' => [
        'theme' => [
            'path' => get_theme_file_path('public'),
            'url' => get_theme_file_uri('public'),
            'assets' => public_path('mix-manifest.json'),
        ]
    ]
```

**Comment by alevgal** [comment]
@slackday thanks for your advice. I just compared all theme files with the repository and updated them
