### ISSUE TITLE
Symfony Error Handler broken

### ISSUE THREAD

**Issue by pxlrbt** [roots/acorn#109]
* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

The Symfony error handler is never rendering which leads to blank pages on errors when `WP_ENV` is not set to `development`

## Steps to reproduce

1. Set `WP_ENV` to "local"
2. Trigger an error/exception

**Expected behavior:** Symfony error page

**Actual behavior:** Blank page

**Reproduces how often:** 100%

## Versions
2.0.1

**Comment by Gandhi11** [comment]
I have the same problem. You only need to install your composer dependencies without the dev dependencies and you will have the problem.

1 - The error needs to be send() to receive the proper html error code.
In the `src/Roots/Acorn/Bootstrap/HandleExceptions.php` file, the method ->send() needs to be append after the render in the renderHttpResponse method. Like so.
```
$this->getExceptionHandler()->render('', $e)->send();
```

2 - The error is not render properly in the page.
In the `/src/Roots/Acorn/Exceptions/Handler.php` file, the render need to be echoed.
```
    public function render($request, Throwable $e)
    {
        try {
            echo app()->environment('development') && class_exists(Whoops::class)
                        ? $this->renderExceptionWithWhoops($e)
                        : $this->renderExceptionWithSymfony($e, app()->environment('development'));
        } catch (Exception $e) {
            echo $this->renderExceptionWithSymfony($e, app()->environment('development'));
        }
    }
```

**Comment by pxlrbt** [comment]
Hey @Gandhi11,
I already opened a PR here: https://github.com/roots/acorn/pull/11
I only changed what you did in your 2. What's the `->send()` for? Will this prevent previous output? I couldn't figure how to prevent that. Maybe you could comment on that PR?

**Comment by Gandhi11** [comment]
If the `->send()` is not used. The page still return a valid 200 OK even if there is a server error.

**Comment by pxlrbt** [comment]
That doesn't work for me:

Currently `$this->getExceptionHandler()->render('', $e)` returns an instance of `Whoops/Run` - which doens't have a `->send` method or string.

With adjustment 2 the return value is `void`.

**Comment by pxlrbt** [comment]
@Gandhi11 
I just looked into this and adjusted my PR so that `Acorn/Exceptions/Handler::render` returns a Symfony Response. Then `->send` can be used on that Response and everything works as expected.
