### ISSUE TITLE
Upstream Loader & registration logic

### ISSUE THREAD

**Issue by mAAdhaTTah** [roots/acorn#11]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing request
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Using annotations to register methods from Service classes to actions / filters.

## Motivation

The idea is to allow you to declare a Service class and annotate its methods, then register said Service with the application container. When the app boots, it loops through all of its services and any with these annotations get registered with WordPress. I did an implementation of the [Loader](https://github.com/intraxia/jaxion/blob/master/src/Core/Loader.php) for an attempt at a similar framework to what Acorn is doing. I would be very interested in upstreaming this to Acorn, if you want it, but wanted to see if that's useful to you first.

## Additional context

I posted about it on [Discourse](https://discourse.roots.io/t/a-workflow-for-modern-wordpress-plugin-development/14990/4?u=maadhattah), and got a like from the OP but no explicit response, so it seems like there may be _some_ interest so thought I'd flag it here.

**Comment by QWp6t** [comment]
Yeah, this sounds interesting. Feel free to get a PR draft started if you want. It doesn't have to be fully fleshed out at first; we can build upon it and discuss it further in the PR.

I've also been thinking about looking into possibly bridging Laravel's event system with WordPress actions.

**Comment by mAAdhaTTah** [comment]
Cool, I'll start digging in. Before I start, what's the intended bootstrapping flow for a plugin using Acorn? Jaxion (the framework w/ the Loader) started off [like this](https://github.com/intraxia/wp-gistpen/blob/next/wp-gistpen.php#L47). That gave me to `boot` method to hook the Loader into and bootstrap all of the classes to WP. How would Acorn handle this?

**Comment by QWp6t** [comment]
We're still working on it, but suffice it to say I think I want it to look something like this...

```php
\Roots\bootstrap(function ($app) {
  $app->register(YourPluginNamespace\YourPluginNameServiceProvider::class);
});
```

A ServiceProvider instance should have the methods `ServiceProvider::register()` and `::boot()`, which will both be run by the Application container during `after_setup_theme` or `rest_api_init`.

Everything in the [Clover](https://github.com/roots/acorn/tree/master/src/Acorn/Clover) namespace is intended to be consumed by plugins. So that might be a good place to add it.

**Comment by Log1x** [comment]
I believe this should effectively be closed with the [rewrite](https://github.com/roots/acorn/blob/master/src/helpers.php#L497-L511) of the bootloader.
