### ISSUE TITLE
[Discussion] Exception handler behaviour

### ISSUE THREAD

**Issue by pxlrbt** [roots/acorn#111]
The exception handler currently has some strange behavior:

1. `WP_DEBUG = true` && `WP_ENV = 'production'` returns a blank page due to [issues with Symfony handler](https://github.com/roots/acorn/issues/109). Also the Symfony handler is pretty useless for debugging. Not sure what's the best way to handle this. 
2. `WP_DEBUG = false` && `WP_ENV = 'production'` doesn't use an Exception Handler and prints PHP warnings/errors depending on WPs `error_reporting` setting. It returns more information than (1) which seems weird, as (1) is "debug mode".
3. `WP_DEBUG = false` && `WP_ENV = 'development'`: Is fine as it is.
4. `WP_DEBUG = true` && `WP_ENV = 'development'` : Returns whoops which is also fine

Generally I think `WP_DEBUG_DISPLAY` would have been a better indicator whether to show an exception handler as it's already a standard within WordPress. But that probably would cause some issue with Sage?!

**Comment by QWp6t** [comment]
Thanks for taking the time to dig into this, and I appreciate your patience.

On the current `next` branch, we use `WP_DEBUG_DISPLAY`. If you're using Sage, you'll have to update config/app.php to reflect that change as well. The Symfony handler should also be working properly.

We will be tagging another beta release shortly. In the meantime, feel free to switch to the `next` branch `composer require roots/acorn dev-next`.
