### ISSUE TITLE
Call to undefined function Illuminate\Foundation\Console\base_path() when publishing

### ISSUE THREAD

**Issue by tombroucke** [roots/acorn#115]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

[Description of the issue]

## Steps to reproduce

1. Clone Sage repo
2. Install package which needs publishing with acorn (like generoi/sage-woocommerce, smarteist/sage-woocommerce)
3. Try publishing files with wp acorn vendor:publish --tag="WooCommerce Templates"

**Expected behavior:**
Files should be copied over to my project

**Actual behavior:**
In VendorPublishCommand.php line 277:
  Call to undefined function Illuminate\Foundation\Console\Roots\base_path()

**Reproduces how often:** 
100%

## Versions

2.0.0-alpha.0

## Additional information

Issue can be resolved by replacing base_path() by \Roots\base_path() in the status() method in roots/acorn/src/Illuminate/Foundation/Console/VendorPublishCommand.php:275

**Comment by QWp6t** [comment]
This is an upstream issue as several Laravel commands require the use of global functions ([x-ref](https://github.com/laravel/framework/pull/36278)).

As a workaround, setting [**config/app.php**@`'globals' => true`](https://github.com/roots/acorn/blob/main/config/app.php#L59-L70) should fix it.

A [future version of Acorn](https://github.com/roots/acorn/tree/next) will pollute the global scope by default to maximize compatibility with Laravel.
