### ISSUE TITLE
component created by default does not work

### ISSUE THREAD

**Issue by ecruhling** [roots/acorn#116]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

On a fresh installation, if you create a component using the CLI, e.g. 'wp acorn make:component Hero', the class for the component does not work correctly, and throws an error.

## Steps to reproduce

1. create a new component via the CLI, e.g. 'wp acorn make:component Hero'
2. add the component into a page template, e.g. '<x-hero></x-hero>'
3. on the page in which you inserted the component, you receive the error: Call to undefined function App\View\Components\view()

**Expected behavior:** The boilerplate code for the component should work without creating an error.

**Actual behavior:** Using the boilerplate code as generated will throw an error.

**Reproduces how often:** 100%

## Versions

Acorn v2.0.0.-alpha.0, Sage v10.0.0dev, MacOS 11.4

## Additional information

Fix: because the namespace on the Class file is incorrect. it is set to: Illuminate\View\Component, while it should be: Roots\Acorn\View\Component. Also the render() function is incorrect, on creation it is: return view('components.test') while it should be: return $this->view('components.test')  (at least according to the included Alert component)

Changing this in ./src/Illuminate/Foundation/Console/stubs/view-component.stub gets it working, and the default component will be created just like the sample Alert component the theme provides.

I created a fork with this fix if you want the commit.

**Comment by QWp6t** [comment]
This should be working in Acorn 2.0.0-beta.0 that was released yesterday.

**Comment by retlehs** [comment]
@LucasDemea hey there, we've verified that this is working as expected on our end. please open up a support request on https://discourse.roots.io/ for further help!
