### ISSUE TITLE
Differing PHP version requirements between dev and regular dependencies

### ISSUE THREAD

**Issue by Bocom** [roots/acorn#124]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Because `pestphp/pest-plugin-mock` was added as a dev dependency, you can no longer install all dependencies on PHP 7, since that Pest plugin requires PHP 8, which means that you can `--no-dev` install on PHP 7.3+ but to develop Acorn itself you need PHP 8.
Was this intentional?

## Steps to reproduce

1. Clone the repo
2. Use PHP 7 (7.4 for example) and `composer install` to install the Composer dependencies

**Expected behavior:**
The installation completes without errors.

**Actual behavior:**
Installation fails because `pestphp/pest-plugin-mock` requires PHP 8.

**Reproduces how often:**
Every time you use PHP 7 to install all dependencies

## Versions
`dev-main`

**Comment by QWp6t** [comment]
Yeah, this was intentional.

PHP 8 is required for Acorn development.

We use PHPCS to ensure that we're not using any language features that require PHP 8.

But the next major version of Acorn will require PHP 8 since Laravel 9 will require PHP 8.
