### ISSUE TITLE
Cannot run commands due to "Fatal error: Trait 'Illuminate\Console\Concerns\CreatesMatchingTest' not found"

### ISSUE THREAD

**Issue by stefanfisk** [roots/acorn#127]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Cannot run any of the `acorn` commands due to  missing `Illuminate\Console\Concerns\CreatesMatchingTest`.

## Steps to reproduce

1. Install `dev-main` in a WordPress project
2. Run `wp acorn`

**Expected behavior:**

It should list the available commands.

**Actual behavior:**

`Roots\Acorn\Bootstrap\RegisterConsole::bootstrap()` throws an unhandled exception because `Illuminate\Foundation\Console\ConsoleMakeCommand` uses `Illuminate\Console\Concerns\CreatesMatchingTest`, which is  not available.

**Reproduces how often:**

Always.

## Versions

Since fe027f1ec9d6af81d6fb8303691e936dd59b0745.

## Additional information

It looks to me like you forgot to copy the `Contracts` folder?

**Comment by stefanfisk** [comment]
I suspect that this might simply have been caused by a messed up `vendor`.

`CreatesMatchingTest` is supplied by `illuminate/console`, which is required by `roots/acorn`, and it all works as expected now.

**Comment by EHLOVader** [comment]
I am getting this error on my theme, I've tried removing vendors and then reinstalling but it doesn't work. 
Using Acorn 2.0.0-beta.2

**Comment by stefanfisk** [comment]
@EHLOVader try doing a `composer update`.

I think that the issue is real, and that the problem is that `CreatesMatchingTest` wasn't added until https://github.com/illuminate/console/commit/9d450507e8106002ec948c7108075cc0a72e5216, which means that if you required `illuminate/console:^8.0` before 2021-10-14 the required trait isn't installed.

The dependency on `illuminate/console` now needs to be `^8.65.0`.

**Comment by QWp6t** [comment]
Thanks @stefanfisk for digging into this
