### ISSUE TITLE
Bug: Issue with Acorn Beta 5+ with Media Cloud plugin

### ISSUE THREAD

**Issue by conradfuhrman** [roots/acorn#157]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

On a new install of Trellis/Bedrock/Sage with and the roots/acorn beta 5 or higher, the Media Cloud plugin cannot be activated. with versions 4.2.36 and/or 4.2.37.

#### What have you tried?

I've tried all the standard troubleshooting. Only plugin active etc. etc... however I started going though the older Acorn versions after an hour or so of troubleshooting and found that beta.4 is the last release that works with this plugin.

#### What insights have you gained?

I believe something was removed (possibly from the dev requirements in acorn?) that might be affecting this specific plugin as it uses Illuminate packages.

#### Possible solutions

Possibly add back the dev dependencies?

#### Temporary workarounds
Downgrade acorn to beta.4 for activation of the plugin and use.

### Steps To Reproduce

1. Install new trellis/bedrock/sage
1. Add media press pro plugin for install
1. Try and activate with acorn-beta.5 or higher

### Expected Behavior

The plugin should activate.

### Actual Behavior

Error seen below.
```
Fatal error: Uncaught BadMethodCallException: Method whenEmpty does not exist.

in /srv/www/mademusicstudio.com/current/web/app/plugins/ilab-media-tools-premium/lib/mcloud-illuminate/support/Traits/Macroable.php:96 Stack trace: #0
/srv/www/mademusicstudio.com/current/web/app/themes/mademusicstudio/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(283): MediaCloud\Vendor\Illuminate\Support\Collection->__call('whenEmpty', Array) #1
/srv/www/mademusicstudio.com/current/web/app/themes/mademusicstudio/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(253): Roots\Acorn\Bootloader->findPath('app') #2
/srv/www/mademusicstudio.com/current/web/app/themes/mademusicstudio/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(206): Roots\Acorn\Bootloader->usePaths() #3
/srv/www/mademusicstudio.com/current/web/app/themes/mademusicstudio/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(181): Roots\Acorn\Bootloader->app() #4
/srv/www/mademusicstudio.com/current/web/wp/wp-includes/class-wp-hook.php(303): Roots\Acorn\Bootloader->__invoke('') #5
/srv/www/mademusicstudio.com/current/web/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #6
/srv/www/mademusicstudio.com/current/web/wp/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #7
/srv/www/mademusicstudio.com/current/web/wp/wp-settings.php(556): do_action('after_setup_the...') #8
/srv/www/mademusicstudio.com/current/web/wp-config.php(9): require_once('/srv/www/mademu...') #9
/srv/www/mademusicstudio.com/current/web/wp/wp-load.php(55): require_once('/srv/www/mademu...') #10
/srv/www/mademusicstudio.com/current/web/wp/wp-admin/admin.php(34): require_once('/srv/www/mademu...') #11
/srv/www/mademusicstudio.com/current/web/wp/wp-admin/plugins.php(10): require_once('/srv/www/mademu...') #12 {main}
thrown in /srv/www/mademusicstudio.com/current/web/app/plugins/ilab-media-tools-premium/lib/mcloud-illuminate/support/Traits/Macroable.php on line 96
```

### Versions

Sage 10.0.0-beta.2

**Comment by QWp6t** [comment]
Media Cloud is using an older version of the Collection class that doesn't have the `whenEmpty()` method (introduced in Laravel 5.7). Acorn is calling the `collect()` global helper, which is being preempted by Media Cloud and causing Acorn (and Laravel components) to use Media Cloud's older Collection method.

Media Cloud will either need to namespace those global helpers or you'll need to load Acorn before loading that plugin to avoid this collision. You can accomplish this by [loading Acorn via Composer in Bedrock](https://docs.roots.io/acorn/2.x/installation/#installing-acorn).

**Comment by conradfuhrman** [comment]
Thanks, I'll try the loading in bedrock to see if it resolves it. It's the most problematic plugin I've had (but the benefits still outweigh the headaches).
