### ISSUE TITLE
Feature Request: bundle()->dequeue

### ISSUE THREAD

**Issue by Striffly** [roots/acorn#196]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Function to dequeue loaded files (js / css)

#### Why are we doing this?

Some pages should not have the JS / CSS used on the rest of the site (for example a redirection page for Internet Explorer on the front, or a style applied only to some pages and not to others in the back-office)

#### What is the expected outcome?

Do not load the JS / CSS 

#### Potential conflicts / foreseeable issues

None ?

**Comment by QWp6t** [comment]
This sounds like it's probably a good idea.

If you want to submit a PR for it, feel free. Otherwise I'll get it in there as time permits.
