### ISSUE TITLE
Bug: Returning component as HTML with render() doesn't pass variables

### ISSUE THREAD

**Issue by Swennet** [roots/acorn#197]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
I want to return a component as an HTML string using blade's `->render()` method, however, no variables are available in the blade view.

### resources/views/components/notice.blade.php
```blade
<div class="{{ $type }}">
  {!! $message !!}
</div>
```

### app/View/Components/Notice.php
```php
<?php

namespace App\View\Components;

use Roots\Acorn\View\Component;

class Notice extends Component
{
    /**
     * The alert type.
     *
     * @var string
     */
    public $type;

    /**
     * The alert message.
     *
     * @var string
     */
    public $message;

    /**
     * The alert types.
     *
     * @var array
     */
    public $types = [
        'default' => 'text-indigo-50 bg-indigo-400',
        'success' => 'text-green-50 bg-green-400',
        'caution' => 'text-yellow-50 bg-yellow-400',
        'warning' => 'text-red-50 bg-red-400',
    ];

    /**
     * Create the component instance.
     *
     * @param  string  $type
     * @param  string  $message
     * @return void
     */
    public function __construct($type = 'default', $message = null)
    {
        $this->type = $this->types[$type] ?? $this->types['default'];
        $this->message = $message;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return $this->view('components.notice');
    }

    public function toHtml()
    {
        return $this->view('components.notice')->render();
    }
}
```

### Returning the notice
```php
function returnErrorNotice() {
    $notice = new Notice('error', __('Invalid email and password combination.'));
    return $notice->toHtml();
}
```

### Steps To Reproduce

1. Create new instance of component class.
2. Try to return class with `->render()` method and variables.
3. No variables are available in the

### Expected Behavior

The rendered view has variables from the Notice.php class available.

### Actual Behavior

There are no variables available in the rendered view.

### Versions

2.0.0

**Comment by QWp6t** [comment]
Thanks for using Acorn.

But I'm not convinced that this is a bug. The way you're trying to do it would require passing the data as the 2nd parameter to `view()` or utilizing the View::with() method.

Feel free to post in Roots Discourse to request support from the community. https://discourse.roots.io/
