### ISSUE TITLE
Bug: version 2.0.2 breaks compatibility with Sage theme

### ISSUE THREAD

**Issue by slackday** [roots/acorn#203]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Version 2.0.2 of Acorn has breaking change with \Roots\bootloader causing error in Sage theme 10.x-dev

Discussion https://discourse.roots.io/t/acorn-failed-to-boot/22458/5

#### What have you tried?

Downgrade to Acorn 2.0.1

#### What insights have you gained?

Error message is probably not helpful but here it is

![156738886-f9505f6e-3435-47f2-9304-df3db1289c7b](https://user-images.githubusercontent.com/154369/156786155-4ec08cac-7e96-4f2a-8043-95ff023c5f06.png)

#### Temporary workarounds

Use fixed version of Acorn by setting `"roots/acorn": "2.0.1",` in `composer.json`

### Steps To Reproduce

1. Run `composer update` on Bedrock/Sage stack

### Expected Behavior

No crash

### Actual Behavior

Crash

### Versions

v2.0.2

**Comment by QWp6t** [comment]
Thank you for reporting this. I'll get this fixed right away.

**Comment by QWp6t** [comment]
It should be resolved with v2.0.3.

The issue was that I accidentally tagged v2.0.2 based off the `main` branch instead of `2.x` branch. 🙊
