### ISSUE TITLE
Feature Request: Add PHP 8.0 support to 1.x

### ISSUE THREAD

**Issue by joshuafredrickson** [roots/acorn#212]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

I have a few older Sage 10 beta (Acorn 1.x) installations that work well on PHP 8 with the exception of Acorn. In order to get these sites working, I forked and created a branch off 1.1.0 with the following change to [composer.json](https://github.com/joshuafredrickson/acorn/blob/69ce04d50ba6f9e0d40a6c88b6aef15690c0fca5/composer.json#L38):

```
"php": "^7.2.5|^8.0",
```

This required a little bit of composer gymnastics in these projects (detailed below if others may find it useful), but it works well beyond that.

#### Why are we doing this?
Adding PHP 8.0 support to Acorn 1.x would allow early pandemic-era Sage sites to run on future versions of PHP without migrating the theme to Acorn 2.x.

### Additional Context

In the interim, for those looking to get Acorn 1.x and PHP 8 working, here are the steps:

- Create a fork and branch with the change to Acorn's `composer.json` described above.
- Add the following to your theme's `composer.json`:
```
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/{github-username}/acorn.git"
    }
  ],
```

- Change the `roots/acorn` version to `dev-{your-fixed-branch} as 1.1.0`. For example:
```
    "roots/acorn": "dev-v1-php-8 as 1.1.0"
```
- Run `composer update`.

**Comment by QWp6t** [comment]
Can you test this for me?

```json
    "roots/acorn": "dev-1.x"
```

I'm assuming that works? I don't have any Acorn v1.x sites to test this with so if you want to try that out for me when you get a chance, I'll tag a proper release once it's confirmed working.

**Comment by joshuafredrickson** [comment]
Requiring `dev-1.x` gives me this:

> Problem 1
>    \- Root composer.json requires roots/acorn dev-1.x, found roots/acorn[dev-dependabot/composer/spatie/temporary-directory-tw-2.1, dev-require-composer-installers, dev-update-laravel-9, dev-main, dev-update-php-8, dev-acorn-dump, dev-bud-rest-api-header, dev-205-support-negatable-options, v1.0.0, ..., 1.x-dev, 2.0.0-alpha.0, ..., 2.x-dev] but it does not match the constraint.

But requiring `1.x-dev` works like a charm. [TIL](https://getcomposer.org/doc/articles/versions.md#branches)

Anyway, yes, the `1.x` branch works as expected with php 8. Thank you!

**Comment by QWp6t** [comment]
I've tagged v1.1.1 with this update. Thanks for reporting this, and thanks for testing!
