### ISSUE TITLE
Bug: Running anything wp acorn results in error

### ISSUE THREAD

**Issue by jackkemmish** [roots/acorn#218]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Running anything `wp acorn` results in this error:
`Error: 'acorn' is not a registered wp command. See 'wp help' for available commands. Did you mean 'core'?`

#### What have you tried?
Installing acorn via composer and running `wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"` for example.

Any help on this would be amazing as I am trying to install blade icons too and having no luck with that either.

Thanks in advance!

Jack

### Steps To Reproduce

1. Run `wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"`
2. Stress out because you've followed all the steps!

### Expected Behavior

I expect the command to run.

### Actual Behavior

Error being thrown.

### Relevant Log Output

```shell
wp acorn vendor:publish --provider="Log1x\AcfComposer\Providers\AcfComposerServiceProvider"                                                                                                                                                                  
Error: 'acorn' is not a registered wp command. See 'wp help' for available commands.
Did you mean 'core'?
```

### Versions

https://github.com/roots/sage/releases/tag/v10.1.6 & macOS Big Sur Version 11.6.4

**Comment by QWp6t** [comment]
Which version of Acorn are you using?

**Comment by jackkemmish** [comment]
Hi @QWp6t, I followed the set up on the Sage docs and composer installed Acorn which installed `"roots/acorn": "^2.0"`.

Thanks,

Jack

**Comment by retlehs** [comment]
@jackkemmish howdy 👋  the issues on this repo are for bugs only and not for support requests

if you search for your error on roots discourse, you'd come across this: https://discourse.roots.io/t/error-acorn-is-not-a-registered-wp-command/19774

try activating your theme? if that doesn't solve your problem, please create a topic over at https://discourse.roots.io/ for support

**Comment by jackkemmish** [comment]
Hi @retlehs my bad! I'll head over to the discourse 🤦‍♂️ 

Thanks!!

Jack
