### ISSUE TITLE
Feature Request: Use spatie/ignition as error page

### ISSUE THREAD

**Issue by rrmesquita** [roots/acorn#221]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Use `spatie/ignition` as error page as opposed to the current one, Whoops.

#### Why are we doing this?

To have a prettier error page.

#### What use cases does it support?

It has a feature for opening the file containing the error on the specific line, which saves some good time when dealing with complex bugs.

#### What is the expected outcome?

Stay up-to-date with Laravel, the framework that Acorn is originally extending from.

#### Potential conflicts / foreseeable issues

Potentially none but I haven't tested, can't be sure.

### Additional Context

Laravel 9.x started using `spatie/ignition`.

**Comment by rrmesquita** [comment]
Let me know if this was already discussed before and if so, why it was chosen to not use Ignition, thanks!

**Comment by retlehs** [comment]
@rrmesquita once the maintainer has a chance, i'm sure they'll be happy to explain. in the meantime, there is no need to bump an issue created ~24 hours ago because you haven't yet gotten a reply. thanks for understanding!

**Comment by Log1x** [comment]
Laravel's Ignition implementation requires routing which is not yet implemented in Acorn.

Related #68

**Comment by Log1x** [comment]
Ignition should now work in Acorn v3 with the introduction of routing.

```sh
$ composer require spatie/laravel-ignition
```

**Comment by dsturm** [comment]
... and just make sure to run `wp acorn package:discover` after requiring per composer, if you want to avoid an hour of debugging, why there i no change of the error handler 🤦‍♂️

**Comment by Log1x** [comment]
Hmm, that generally shouldn't happen.

Are you by any chance missing the `post-autoload-dump` in your `composer.json` from the [Acorn installation docs](https://roots.io/acorn/docs/installation/#installing-acorn-with-composer)?

**Comment by dsturm** [comment]
That's why I didn't thought of this. But yeah, the `post-autoload-dump` exists in `composer.json` - I'm using a `bedrock` and `sage` project from late 2022 and manually upgraded to the latest changes.
