### ISSUE TITLE
Asset handles shouldn't change - now contains an index in the handle

### ISSUE THREAD

**Issue by davidwebca** [roots/acorn#225]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Bundle.php enqueues CSS with an asset ID that changes depending on the number of assets because the ID is generated through a loop.
https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Assets/Bundle.php#L54
https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Assets/Bundle.php#L77

#### What have you tried?
I tried to enqueue a localized script which fails to be predictable because of the number of assets that changes depending on different conditions such as the number of entry points in bud.
wp_localize_script( 'sage/app.js' ... )

#### What insights have you gained?
A number from an array that can change easily by enqueueing additional assets shouldn't be added to the handle to make sure the asset id is predictable.

#### Possible solutions
Generate a handle from the file name with basename() or simply use the full file name which is valid too I think. 🤔 

#### Temporary workarounds
```php
$id = bundle('app')->js()->search(function($item) {
    return $item == "app.js";
});
$handle = "app/$id";
wp_localize_script( $handle, ...);
```

### Steps To Reproduce

1. Enqueue regular assets in Sage
2. Use wp_localize_script
3. Add more entry points in bud.js 
4. Notice the entry index shift and wp_localize_script breaks

### Expected Behavior

Use a more simple handle that never changes based on the file name.

### Actual Behavior

wp_localize_script, and other enqueueing dependencies, needs to be re-adjusted every time a new entry points is added.

### Versions

2.0.3

**Comment by QWp6t** [comment]
Use the `Bundle::localize()` method.

```php
add_action('wp_enqueue_scripts', function () {
    bundle('app')->enqueue()->localize('example', ['hello' => 'world']);
}, 100);
```
