### ISSUE TITLE
Full Site Editing (FSE) support (frontend)

### ISSUE THREAD

**Issue by strarsis** [roots/acorn#228]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Full Site Editing (FSE) with Sage 10 theme loads a blade template in frontend, no Website editor blocks are shown.

## Steps to reproduce
1. Ensure a Sage 10 theme is present and enabled.
2. Enable Full Site Editing (FSE) support in the Sage 10 theme.
3. Add some modifications to the Website editor.
4. Add/edit a page (front page).
5. Open the front page on frontend.
Note that the site blocks from the Website editor are not loaded, instead the default blade-based template.

**Expected behavior:**
Frontend shows the blocks from website editor.

**Actual behavior:**
Frontend doesn't show the blocks from website editor, but the default blade template instead.

**Reproduces how often:**
Always.

## Versions
`1.16.1: 2021-07-30`

## Additional information
Latest Gutenberg plugin `11.7.1`.

The previous code for adding compatibility for Full Site Editing (FSE) doesn't work (anymore):
```php
// Sage 10 + Gutengberg Full Site Editing (FSE) template compatibility
// @see https://discourse.roots.io/t/sage-10-block-based-theme-support/17294/2?u=strarsis
add_filter('template_include', function ($template_file) {
    global $_wp_current_template_hierarchy;
    $_wp_current_template_hierarchy = array_map('basename', $_wp_current_template_hierarchy);
    return $template_file;
}, 19);

````

**Comment by strarsis** [comment]
Demo Sage 10 theme with Full Site Editing / Block Templates and Partials, see this post:
https://github.com/roots/acorn/pull/141#issuecomment-1287831709

**Comment by strarsis** [comment]
Somewhere I read about the idea to use Blade-PHP as Full Site Editing Block (FSE) Block Templates and Partials (but can't find it right now).
That means that Blade-PHP templates are used, compiled and then used for Block Templates and Block Partials.
From the current state of WordPress core and Gutenberg Plugin template handling, it appears that this may be possible.

**Comment by QWp6t** [comment]
Thanks for taking the lead on this feature strarsis. We finally tested and got your PR merged.
