### ISSUE TITLE
Bug: enqueueCss() not working as expected

### ISSUE THREAD

**Issue by tedw** [roots/acorn#229]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

`enqueueCss()` doesn’t work when there’s only a single CSS file as the entry point.

```js
bud.entry({
  app: ['@scripts/main', '@styles/main.scss'],
  login: '@styles/login.scss'
})
  .splitChunks(false)
  .runtime(false)
  .assets('images')
  .watch('resources/views/**/*', 'app/**/*')
  .proxy('http://my-app-name.lndo.site')
  .serve('http://localhost:3000');
```

```php
add_action('login_enqueue_scripts', function() {
    bundle('login')->enqueueCss();
});
```

#### What have you tried?

It works if you add another file to the `login` entry. It also works if you downgrade `@roots/bud` to version `5.8.3` and use `enqueue()` instead. However, starting at version `5.8.4` neither `enqueueCss()` nor `enqueue()` works when there is a single file.

#### What insights have you gained?

I suspect this Bud update below is reason why it’s failing, but I think the root cause is with Acorn.
- Issue https://github.com/roots/bud/issues/1416
- PR https://github.com/roots/bud/pull/1417

Here’s the error message:

<img width="691" src="https://user-images.githubusercontent.com/864716/171279350-4a6a3c51-c5ac-45d1-8b6e-5aff178f11c8.png">

Here’s the relevant line in `/app/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php:36`

https://github.com/roots/acorn/blob/53cba94831f330d1331a0bfac4ff045bf5044f8e/src/Roots/Acorn/Assets/Bundle.php#L136

#### Possible solutions

I’m not super familiar with the codebase yet but I’m hoping it’s as easy as updating the line referenced above.

#### Temporary workarounds

Create an empty JS file and add it to the entry point:

```js
bud.entry({
  app: ['@scripts/main', '@styles/main.scss'],
  login: ['@scripts/empty', '@styles/login.scss']
})
```

Another option is to downgrade to Bud `5.8.3` and use `enqueue()`.

### Steps To Reproduce

1. Add a single CSS as an entry point in `bug.config.js`
1. Attempt to enqueue that CSS file using `bundle('example')->enqueueCss();`
1. Run `bud build`
1. Open page that should have the custom CSS file in the browser

### Expected Behavior

The CSS file should have been enqueued normally.

### Actual Behavior

An error was thrown

### Relevant Log Output

```shell
Fatal error: Uncaught Error: Argument 1 passed to Illuminate\Support\Arr::isAssoc() must be of the type array, null given, called in /app/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php on line 136
in /app/vendor/illuminate/collections/Arr.php on line 406

Call stack:

Illuminate\S\Arr::isAssoc()
/app/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php:136
Roots\A\A\Bundle::setRuntime()
/app/vendor/roots/acorn/src/Roots/Acorn/Assets/Bundle.php:36
Roots\A\A\Bundle::__construct()
/app/vendor/roots/acorn/src/Roots/Acorn/Assets/Manifest.php:56
Roots\A\A\Manifest::bundle()
/app/vendor/roots/acorn/src/Roots/helpers.php:36
Roots\bundle()
wp-content/themes/[redacted]/app/setup.php:19
App\{closure}()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-login.php:114
login_header()
wp-login.php:1383
```

### Versions

Sage 10, Acorn 2.0.6, Bud 5.8.0

**Comment by QWp6t** [comment]
Fixed in #230 (https://github.com/roots/acorn/commit/4fd1c43b0bb255daaa0a137cd30dc0aad39216b2)
