### ISSUE TITLE
Bug: 2.1.1 causes JS to break in production

### ISSUE THREAD

**Issue by theimaginaire** [roots/acorn#241]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

Upgrading Acorn to 2.1.1 from 2.1.0 causes javascript to break in production. The website is finding the app.js files, but for some reason they're not actually triggering.

#### What have you tried?

Running yarn cache clean and yarn build, to no avail.

Only fix was to downgrade acorn to previous version.

#### Temporary workarounds

Downgrade acorn to 2.1.0 and javascript starts working again.

### Steps To Reproduce

1. Upgrade acorn on a working website to 2.1.1
2. Run yarn build
3. Try loading the website and javascript will be broken
4. Downgrade to 2.1.0 
5. Run yarn build
6. Open website and javascript will be working again 

### Expected Behavior

Javascript to continue working

### Actual Behavior

Javascript breaks

### Relevant Log Output

```shell
No console errors, yarn errors etc.
```

### Versions

2.1.1

**Comment by retlehs** [comment]
> The website is finding the app.js files, but for some reason they're not actually triggering.

can you be more specific please?

can you also provide either a git repo or provide all of the changes you've made to your theme that are required to reproduce the bug?
