### ISSUE TITLE
Bug: Page template dropdown disappeared after upgrading to Acorn v3.x

### ISSUE THREAD

**Issue by Twansparant** [roots/acorn#247]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
After upgrading **Acorn** to the `3.0.0-alpha.3` version (but it also happens on alpha.1 & alpha.2), the **Template** dropdown in the **Page attributes** metabox has completely disappeared somehow.
When viewing my template sin the frontend I get a `Target class [sage.view] does not exist.` error?

#### What have you tried?

- I tried installing all 3.0.0-alpha versions and running all of these commands afterwards:
```
wp acorn acorn:init
wp acorn package:discover
wp acorn vendor:publish
wp acorn config:clear
wp acorn optimize:clear
wp acorn optimize
wp acorn view:cache
```
All without errors and I can also see my `log1x/acf-composer` fields & `log1x/poet` types in the backend.

- I disabled all of my plugins.
- I disabled all of my wordpress actions/filters in my theme.

#### What insights have you gained?
I think Acorn possible is not recognising my template files inside the `resources/views` folder even though `get_theme_file_path('/resources/views')` is returning the correct path?

#### Possible solutions
Downgrading to **Acorn 2.1**, but then I'm bumping into [this bug](https://github.com/roots/acorn/issues/217#issuecomment-1227082330) again.

#### Temporary workarounds
Switch to a default Wordpress theme

### Steps To Reproduce

1. Install roots/acorn 3.0.0-alpha.3 with composer in your Bedrock folder:
`composer require roots/acorn:3.0.0-alpha.3`
2. Call the bootloader in your **functions.php**:
`\Roots\bootloader()->boot();`
3. Go to an edit page in your Wordpress backend and have a look at the **Page attributes** box in the right sidebar.
4. Switch to a default Wordpress theme and repeat step 3.

### Expected Behavior

The **Page attributes** box in the right sidebar should have a **Template** dropdown.

### Actual Behavior

The **Page attributes** box in the right sidebar does not have a **Template** dropdown anymore.

### Relevant Log Output

No php errors whatsoever

### Versions

Acorn 3.0.0-alpha.3 PHP 8.0.22 Composer version 2.4.1

**Comment by QWp6t** [comment]
I noticed that you updated `functions.php` to have `\Roots\bootloader()->boot()`, but did you also make sure your [`ThemeServiceProvider`](https://github.com/roots/sage/blob/main/app/Providers/ThemeServiceProvider.php) extends [`SageServiceProvider`](https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Sage/SageServiceProvider.php)?

Also, did you check your logs? There might not be any by default unless you've run `wp acorn vendor:publish --tag=acorn:init` and updated `config/logging.php`. But the logs could provide a clue as to what's going on, such as if a provider is failing to register or boot.

**Comment by Twansparant** [comment]
> but did you also make sure your [`ThemeServiceProvider`](https://github.com/roots/sage/blob/main/app/Providers/ThemeServiceProvider.php) extends [`SageServiceProvider`](https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Sage/SageServiceProvider.php)

Yup checked it, and it does extend the `SageServiceProvider`.
In my logs there's a bunch of these:

```
Next Illuminate\Contracts\Container\BindingResolutionException: Target class [assets.manifest] does not exist. in /srv/www/mydomain.com/current/vendor/illuminate/container/Container.php:877
Stack trace:
#0 /srv/www/mydomain.com/current/vendor/illuminate/container/Container.php(756): Illuminate\Container\Container->build('assets.manifest')
#1 /srv/www/mydomain.com/current/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(855): Illuminate\Container\Container->resolve('assets.manifest', Array, true)
#2 /srv/www/mydomain.com/current/vendor/illuminate/container/Container.php(692): Illuminate\Foundation\Application->resolve('assets.manifest', Array)
#3 /srv/www/mydomain.com/current/vendor/roots/acorn/src/Illuminate/Foundation/Application.php(840): Illuminate\Container\Container->make('assets.manifest', Array)
#4 /srv/www/mydomain.com/current/vendor/roots/acorn/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application->make('assets.manifest', Array)
#5 /srv/www/mydomain.com/current/vendor/roots/acorn/src/Roots/helpers.php(21): app('assets.manifest')
#6 /srv/www/mydomain.com/current/web/app/themes/sage/app/setup.php(185): Roots\asset('editor.css')
#7 /srv/www/mydomain.com/current/web/wp/wp-includes/class-wp-hook.php(307): App\{closure}('')
#8 /srv/www/mydomain.com/current/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#9 /srv/www/mydomain.com/current/web/wp/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#10 /srv/www/mydomain.com/current/web/wp/wp-settings.php(576): do_action('after_setup_the...')
#11 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1271): require('/srv/www/cms.cl...')
#12 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1192): WP_CLI\Runner->load_wordpress()
#13 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#14 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(77): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#16 phar:///usr/bin/wp/php/boot-phar.php(11): include('phar:///usr/bin...')
#17 /usr/bin/wp(4): include('phar:///usr/bin...')
#18 {main}
  thrown in /srv/www/mydomain.com/current/vendor/illuminate/container/Container.php on line 877
[25-Aug-2022 19:20:55 UTC] PHP Parse error:  Unclosed '{' on line 215 in /srv/www/mydomain.com/current/web/app/themes/sage/app/setup.php on line 235
```
I get these logs after following these steps:
1. Update Acorn to 3.0.0-alpha.3 and run `rm rf vendor && rm composer.lock && composer install`
2. `rm -rf /site/web/app/cache`
3. Adjust my theme **functions.php** and add `\Roots\bootloader()->boot()` and remove `add_theme_support('sage')` like stated in the docs.
4. Run these Acorn commands:
```
wp @development acorn acorn:init
wp @development acorn vendor:publish
wp @development acorn optimize
```
Am I missing a step?
Thanks!

**Comment by QWp6t** [comment]
It's looking to me like the ThemeServiceProvider isn't getting loaded.

Does **app/themes/sage/composer.json** list ThemeServiceProvider as a provider? 


For reference, here is how we do it in the current stable version of Sage: https://github.com/roots/sage/blob/main/composer.json#L63-L69

**Comment by retlehs** [comment]
Would you mind submitting a topic on Roots Discourse and possibly provide a repo for someone to try to reproduce? I'm unable to confirm this bug with Acorn v3

**Comment by oxyc** [comment]
Did you notice it moved from _page attributes_ to it’s own separate _template_ pabel? i was unable to see the panel in the ui until i found it in the codebase

https://github.com/WordPress/gutenberg/pull/30900#issuecomment-822379508

**Comment by Twansparant** [comment]
> Did you notice it moved from page attributes to it’s own separate template panel?

Yeah I did notice that, but only if you have enabled Gutenberg, which I haven't for this theme.

**Comment by felly** [comment]
I had the same `Target class [sage.view] does not exist.` error. I forgot to call the parent's `register()`/`boot()` methods.

Here is my working `ThemeServiceProvider`:

```php
<?php

namespace App\Providers;

use Roots\Acorn\Sage\SageServiceProvider;

class ThemeServiceProvider extends SageServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        parent::register();
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
    }
}
```
