### ISSUE TITLE
public_path helper points to non-default Sage publicPath

### ISSUE THREAD

**Issue by knowler** [roots/acorn#25]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

The `public_path()` helper is pointing to the `public` directory in Sage which doesn't exist. I think we gotta either tie this into the asset manager or drop it. I’m leaning towards the latter since personally, I don't think `public_path` makes sense in the context of a WordPress theme or plugin since everything is public. On the other hand, Laravel Mix uses this terminology so that could be a reason to keep it.

**Comment by QWp6t** [comment]
We could make it the same as webpack's and mix's publicPath, which would be the dist directory. I'm not sure if that's useful, however.

**Comment by Log1x** [comment]
ideally I'd like to make it the current manifest path

**Comment by QWp6t** [comment]
You can set it to whatever you want now.

https://github.com/roots/acorn/blob/master/src/Acorn/Concerns/Application.php#L207-L217
