### ISSUE TITLE
Bug: Fatal Error on Deleting Attachments 

### ISSUE THREAD

**Issue by mikiamomik** [roots/acorn#253]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
When I try to delete an attachment from media this error appears "Error in deleting the attachment."
```
Fatal error: Uncaught Error: array_map(): Argument #2 ($array) must be of type array, WP_Error given
in /home/customer/www/ysite.com/public_html/releases/43/web/wp/wp-includes/taxonomy.php on line 1924

Call stack:

array_map()
wp-includes/taxonomy.php:1924
wp_delete_object_term_relationships()
wp-includes/post.php:6378
wp_delete_attachment()
wp-includes/post.php:3363
wp_delete_post()
wp-admin/includes/ajax-actions.php:856
wp_ajax_delete_post()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-admin/admin-ajax.php:187
Query Monitor
There has been a critical error on this website.
```

I understood that the problem comes from acorn as I commented in functions.php the underlying code part, everything works

```
try {
    \Roots\bootloader();
} catch (Throwable $e) {
    wp_die(
        __('You need to install Acorn to use this theme.', 'sage'),
        '',
        [
            'link_url' => 'https://docs.roots.io/acorn/2.x/installation/',
            'link_text' => __('Acorn Docs: Installation', 'sage'),
        ]
    );
}
```

#### Possible solutions
I don't know

#### Temporary workarounds
I don't know

### Steps To Reproduce

1. go to Media
2. open an attachment (image or file)
3. try to delete it permanently

![Uploading Screenshot 2022-11-21 at 12.22.03.png…]()

### Expected Behavior

![Screenshot 2022-11-21 at 12 22 07](https://user-images.githubusercontent.com/2934487/203038294-2fc02289-6757-412f-a166-e9312b58d235.png)

### Actual Behavior

//

### Relevant Log Output

```shell
Fatal error: Uncaught Error: array_map(): Argument #2 ($array) must be of type array, WP_Error given
in /home/customer/www/ysite.com/public_html/releases/43/web/wp/wp-includes/taxonomy.php on line 1924

Call stack:

array_map()
wp-includes/taxonomy.php:1924
wp_delete_object_term_relationships()
wp-includes/post.php:6378
wp_delete_attachment()
wp-includes/post.php:3363
wp_delete_post()
wp-admin/includes/ajax-actions.php:856
wp_ajax_delete_post()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-admin/admin-ajax.php:187
Query Monitor
There has been a critical error on this website.
```

### Versions

2.1.2

**Comment by Log1x** [comment]
This can not be reproduced on a fresh install of Sage 10 + Acorn and your log output has nothing to do with Acorn.

The only reason Acorn is involved is because it's catching an error that'd otherwise go uncaught. I assume you will have no problems if you disable `WP_DEBUG` but I suggest you find the underlying problem/plugin causing the issue.
