### ISSUE TITLE
Bug: Using `asset()` helper causes failures when running WP-CLI commands

### ISSUE THREAD

**Issue by retlehs** [roots/acorn#263]
### Description

The `asset` function works until a `wp` command is ran

### Steps To Reproduce

1. Use the `asset()` helper in a PHP file:

```php
add_action('init', function () {
    $test = asset('editor.css');
});
```

2. Run `wp`

### Actual Behavior

```
Fatal error: Uncaught ReflectionException: Class "assets.manifest" does not exist in /srv/www/example.com/current/web/app/themes/sage/vendor/illuminate/container/Container.php:893
```

### Versions

v3.0.0

**Comment by QWp6t** [comment]
Hey @retlehs 👋

Thanks for reporting this! 🙏

I'll look into it this weekend and see about getting a fix implemented!

**Comment by retlehs** [comment]
Note: Others may also be getting this same error message in a situation that is **unrelated to this bug** — this is the result of having an outdated `config/app.php` file in your setup. If you're running into this error and _aren't_ using the `asset()` helper, see the [Upgrade Guide](https://roots.io/acorn/docs/upgrading-acorn/) for info

**Comment by retlehs** [comment]
FWIW, the hook used definitely matters, too:

* ✅ Using `asset()` in `wp_head` 
* :x: Using `asset()` in `init` 
* :x: Using `asset()` in `after_setup_theme`

**Comment by Twansparant** [comment]
Don't know if it's related, but running `wp acorn optimize` without the `asset()` function call, results in an error:
```shell
In ConfigCacheCommand.php line 84:
                                                  
  Your configuration files are not serializable.  
                                                  

In config.php line 336:
                                                   
  Call to undefined method Closure::__set_state()  
                                                   
```

**Comment by QWp6t** [comment]
@Twansparant 

That looks to me like there are some closures getting into your config somewhere, which aren't serializable out of the box and should be avoided in your configs.

It's also possible that we missed a dependency from Laravel 9 that we need to get in there, such as [laravel/serializable-closure](https://github.com/laravel/serializable-closure).

I'll dig into these issues tomorrow.

**Comment by Twansparant** [comment]
> That looks to me like there are some closures getting into your config somewhere, which aren't serializable out of the box and should be avoided in your configs.

This error was caused by my `[log1x/poet](https://github.com/Log1x/poet)` config file.
I was using the [Extended CPTs Admin Columns Custom Function](https://github.com/johnbillion/extended-cpts/wiki/Admin-columns#custom-function) in a few of my CPT.

I moved my function to a class like suggested [here](https://github.com/getsentry/sentry-laravel/issues/266), and the error is gone!
