### ISSUE TITLE
Feature Request: Set script translations for a bundle 

### ISSUE THREAD

**Issue by Dathix** [roots/acorn#273]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Provide a way to set script translations for a bundle to be used by `wp.i18n`.

#### Why are we doing this?
To enable the use of `wp.i18n` inside a bundle.

#### What use cases does it support?
Use WordPress translations inside scripts. 

#### What is the expected outcome?
The provided script translations need to be set for every handle. 

#### Potential conflicts / foreseeable issues
None

**Comment by strarsis** [comment]
Adding translation support by default is a good idea, as Sage (that uses `acorn`) is already fully supporting translation.
