### ISSUE TITLE
Add `about` command

### ISSUE THREAD

**Issue by retlehs** [roots/acorn#279]
Add `about` command to show some app information about Laravel, WordPress, and Acorn versions, along with URL/path info, and some WordPress health check statuses

Screenshot of WIP from @QWp6t:

![image](https://user-images.githubusercontent.com/115911/221376997-16a35631-82b5-4913-b739-996bc750f802.png)

Ref https://blog.laravel.com/laravel-new-about-command

**Comment by QWp6t** [comment]
I wrote that before Laravel had released theirs. They had posted screenshots about it on Twitter and I was inspired to create something similar, but it resulted in me manually creating that table view and figuring out some math for proper alignment.

I mention this only to say that it means I'll need to do a significant refactor to have it use the termwind component stuff they have now. But the end result will be better and easier to maintain. I'll see if I can do that this weekend. 👍🏼
