### ISSUE TITLE
No changelog or easily-discernable version number in repo source

### ISSUE THREAD

**Issue by montchr** [roots/acorn#284]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

The issue template asks for a version number but:

- It suggests looking in `CHANGELOG.md`, which does not exist
- `composer.json` does not provide a version number

### Steps To Reproduce

1. See issue template

### Expected Behavior

A version number is easily visible in the project source.

### Actual Behavior

No changelog, no version in composer manifest.

### Versions

?

**Comment by retlehs** [comment]
I'll get the issue template updated.

You can do `composer show roots/acorn`.

There's also https://github.com/roots/acorn/blob/2ccffc169f9dba05499f7dbb6e2d30f2809312de/src/Roots/Acorn/Application.php#L31.
