### ISSUE TITLE
make:composer command should add new composer to config

### ISSUE THREAD

**Issue by knowler** [roots/acorn#29]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

`wp acorn make:composer` should add new composer to composers in `config/view.php`.

**Comment by Log1x** [comment]
As far as I know, there's no convenient way to write to config files in Laravel's core at the moment. Third party packages do exist for this, however.

I'm kind of thinking we just autoload `Composers` and `Providers` that are in the `app/` directory. We are already autoloading providers from vendors during `composer dump-autoload` as well as autoloading `Commands`– so we might as well + it might be less confusing for people in the long-run.

**Comment by QWp6t** [comment]
I'm fine with that as long as we're not assuming the `App` namespace. There should be a `getNamespace()` helper function ... somewhere. I believe it's on the application container. We use it in a couple commands already.

**Comment by Log1x** [comment]
This is no longer necessary as of #32.
