### ISSUE TITLE
💡 Feat req: Use bladestan for linting of blade templates 

### ISSUE THREAD

**Issue by chrillep** [roots/acorn#290]
### Summary

* Use bladestan for linting blade templates
* add bladestan to CI workflow

ref: 
* [https://github.com/tomasVotruba/bladestan 3](https://github.com/tomasVotruba/bladestan)
* [https://github.com/roots/sage/issues/3139 7](https://github.com/roots/sage/issues/3139)
* https://discourse.roots.io/t/feat-req-radicle-sage-use-bladestan-for-linting-of-blade-templates/25461
* https://github.com/roots/sage/issues/3139

**Comment by QWp6t** [comment]
Where do you see this being used in Acorn?

There are no blade templates in this repository.

**Comment by QWp6t** [comment]
Closing this for now since I don't really see where this fits into Acorn.

Feel free to reply here and tag me if you think I'm missing something.

**Comment by chrillep** [comment]
no. Your right! Im probably just confused 😄 
not sure what i was thinking 🤔 .
