### ISSUE TITLE
`basePath()` doesn't use `match` properly

### ISSUE THREAD

**Issue by htmlburger-git** [roots/acorn#307]
### Version

3.2

### What did you expect to happen?

to be able to boot the app

### What actually happens?

it didn't boot the app

### Steps to reproduce

https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Bootloader.php#L300-L319

Create an app without any of the folowing:
```
$_ENV['APP_BASE_PATH'],
constant('ACORN_BASEPATH'),
get_theme_file_path('composer.json')
get_theme_file_path('app')
```

It's supposed to get the path from this match branch:

```
$vendor_path = (new Filesystem())->closest(dirname(__DIR__, 4), 'composer.json')) => dirname($vendor_path
```

However, it doesn't because match expression requires boolean value in, and `$vendor_path` is a string. As a result, it falls back to 
```
            default => dirname(__DIR__, 3)
```

See: https://www.php.net/manual/en/control-structures.match.php
```
A match arm compares values strictly (===) instead of loosely as the switch statement does.
```

### Please confirm this isn't a support request.

Yes

**Comment by QWp6t** [comment]
Thanks for the heads up! 🙏
