### ISSUE TITLE
Custom file with wp-load loads wp-cli

### ISSUE THREAD

**Issue by Koniciuaaa** [roots/acorn#309]
### Version

3.0

### What did you expect to happen?

I have integration.php file in main wordpress folder.

In the beginning of this file I included wp-load.php

I need to do this instead:
`\Roots\bootloader()->boot(function($app) {

    if ($app->hasBeenBootstrapped()) {
        return;
    }

    return $app->make(\Illuminate\Contracts\Http\Kernel::class)
        ->handle(\Illuminate\Http\Request::capture());
});`

### What actually happens?

When I want to run this file by CLI wp-cli is running and file is not running properly.

### Steps to reproduce

Run custom file with wp-load.php in the begining

### Please confirm this isn't a support request.

Yes

**Comment by QWp6t** [comment]
We only load the wp-cli kernel if the WP_CLI class exists, which presumably is only present if you're running wp-cli, in which case it makes sense that Acorn would load in wp-cli.

![image](https://github.com/roots/acorn/assets/2104321/8a2d6b6e-dd73-4d80-becb-e0ad7c0cf4e3)

Your solution for specifying the Http kernel makes sense.

I would not consider this a bug.

We have an issue to document how to specify a separate kernel, similar to what you've done.

I'm going to close this out in favor of https://github.com/roots/docs/issues/507
