### ISSUE TITLE
Changes to WordPress routes break the wp-admin login

### ISSUE THREAD

**Issue by dsturm** [roots/acorn#337]
### Version

v4.0.0

### What did you expect to happen?

Login into backend works as usual

### What actually happens?

After submitting the login credentials, I'll be "redirected" to the login form. On first attempt WordPress hints that cookies might be forbidden / deactivated.

### Steps to reproduce

- Upgrade to v4.0.0
- Try to login from `wp-login.php`

**Comment by retlehs** [comment]
Thanks for reporting this!

## Temporary workarounds

* Revert to ` v4.0.0-beta.1`
* Use the [WP-CLI login command](https://github.com/aaemnnosttv/wp-cli-login-command)

**Comment by tedw** [comment]
Same issue, had to downgrade to v3

**Comment by retlehs** [comment]
Give #339 a shot?

`composer require roots/acorn dev-router-wp-login`

**Comment by tedw** [comment]
Upgrading to `v4.0.2` fixed the issue for me 👍
