### ISSUE TITLE
WP ACORN commands not working

### ISSUE THREAD

**Issue by natanael-aguiar** [roots/acorn#351]
### Version

4

### What did you expect to happen?

I expected that when running the wp acorn list command as described in the documentation, the list of commands available to me would be presented.

### What actually happens?

When running the wp acorn list command, the following error occurs:

Fatal error: Declaration of Illuminate\Console\Application::add(Symfony\Component\Console\Command\Command $command) must be compatible with Symfony\Component\Console\Application::add(Symfony\Component\Console\Command\Command $command): ?Symfony\Component\Console\Command\Command in /var/www/html/vendor/illuminate/console/Application.php on line 211

![image](https://github.com/roots/acorn/assets/72773757/6407bcf0-2126-4e60-b5e9-29da7beaf07a)

### Steps to reproduce

Just install Acorn with the Sage theme and try running some Acorn commands.

### System info

Windows 11 with WSL 2, Docker and DDEV

### Log output

[19-Feb-2024 17:52:50 UTC] PHP Fatal error:  Declaration of Illuminate\Console\Application::add(Symfony\Component\Console\Command\Command $command) must be compatible with Symfony\Component\Console\Application::add(Symfony\Component\Console\Command\Command $command): ?Symfony\Component\Console\Command\Command in /var/www/html/vendor/illuminate/console/Application.php on line 211

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
How did you install Acorn?

Are you running the `wp` commands from your DDEV container that has WordPress? I think you can just do `ddev wp acorn`?

**Comment by natanael-aguiar** [comment]
I installed Acorn using composer in the Bedrock root. I have already run the command ex: ddev wp acorn list. See the error presented and a screenshot:

![image](https://github.com/roots/acorn/assets/72773757/53caab8f-d298-4c30-84ba-de9824033587)

**Comment by natanael-aguiar** [comment]
As incredible as it may seem, the error I described was related to the use of Pest https://pestphp.com/ in my Sage theme, I removed Pest, added PHPUnit and everything worked normally.

**Comment by mha-baernholdt** [comment]
> As incredible as it may seem, the error I described was related to the use of Pest https://pestphp.com/ in my Sage theme, I removed Pest, added PHPUnit and everything worked normally.

can you elaborate what you did to fix this, i have the same issue also using the sage them, but i don't see where pest is used.

**Comment by TimAtTeamlemke** [comment]
Same error here after configuring the sage theme to use scss instead of css and replacing tailwind with bootstrap and installing blade icons.
After that "$ wp acorn vendor:publish --tag=blade-icons" could no longer be executed. Blank installation.
When I removed all the packages and dependencies, I was able to execute wp acorn commands again.

**Comment by Log1x** [comment]
> After that "$ wp acorn vendor:publish --tag=blade-icons" could no longer be executed. Blank installation.

Make sure Blade Icons and Acorn are installed in the same `composer.json` - if not, Laravel packages will install a conflicting version of Laravel dependencies.
