### ISSUE TITLE
Admin pages are broken in multisite with subfolder structure

### ISSUE THREAD

**Issue by tombroucke** [roots/acorn#355]
### Version

4.x

### What did you expect to happen?

I have a multisite: `https://multisite.local`, with one subsite in a subfolder structure: `https://multisite.local/test`.

On the multisite's subsite, all admin pages (e.g. `https://multisite.local/test/wp-admin/edit.php`, `https://multisite.local/test/wp-admin/post.php?post=1&action=edit`) except for the dashboard (`https://multisite.local/test/wp-admin/`) are broken.

I expected to see the admin pages and be able to edit posts.

I did some logging, and found out that `$pathInfo` in `vendor/symfony/http-foundation/Request.php:1907` contains the incorrect value (`-admin/post.php`). 

### What actually happens?

**In development:**
Laravel's 404 | Not found 

**In production:**
There has been a critical error on this website.
[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

### Steps to reproduce

Bedrock + sage + multisite with subfolder structure

### Log output

```shell
[13-Mar-2024 12:28:11 UTC] PHP Fatal error:  Uncaught Symfony\Component\HttpKernel\Exception\NotFoundHttpException: The route hp could not be found. in /Users/tombroucke/Local/multisite/app/vendor/illuminate/routing/AbstractRouteCollection.php:44
Stack trace:
#0 /Users/tombroucke/Local/multisite/app/vendor/illuminate/routing/RouteCollection.php(162): Illuminate\Routing\AbstractRouteCollection->handleMatchedRoute(Object(Illuminate\Http\Request), NULL)
#1 /Users/tombroucke/Local/multisite/app/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(215): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#2 /Users/tombroucke/Local/multisite/app/vendor/roots/acorn/src/Roots/Acorn/Bootloader.php(118): Roots\Acorn\Bootloader->bootHttp(Object(Roots\Acorn\Application))
#3 /Users/tombroucke/Local/multisite/app/web/app/themes/test/functions.php(43): Roots\Acorn\Bootloader->boot()
#4 /Users/tombroucke/Local/multisite/app/web/wp/wp-settings.php(611): include('/Users/tombrouc...')
#5 /Users/tombroucke/Local/multisite/app/web/wp-config.php(9): require_once('/Users/tombrouc...')
#6 /Users/tombroucke/Local/multisite/app/web/wp/wp-load.php(55): require_once('/Users/tombrouc...')
#7 /Users/tombroucke/Local/multisite/app/web/wp/wp-admin/admin.php(34): require_once('/Users/tombrouc...')
#8 /Users/tombroucke/Local/multisite/app/web/wp/wp-admin/post.php(12): require_once('/Users/tombrouc...')
#9 {main}
  thrown in /Users/tombroucke/Local/multisite/app/vendor/illuminate/routing/AbstractRouteCollection.php on line 44
```

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Thank you for reporting this! I've noticed on a non-multisite setup that `The route hp could not be found` error also can be triggered from visiting these URLs:

```
https://example.com//wp//xmlrpc.php
https://example.com//wp//wp-admin/admin.php
https://example.com//wp//wp-login.php
```
