### ISSUE TITLE
Upgrading from v3.0 to v4.0 | MonoLog\Logger must be compatible with Psr\Log\LoggerInterface

### ISSUE THREAD

**Issue by YasserB94** [roots/acorn#372]
### Version

3.0 => 4.0

### What did you expect to happen?

Following [the documentation](https://roots.io/acorn/docs/upgrading-acorn/), I upgraded Acorn from ^3.0 to ^4.0. 
I expected this to be a normal version bump.

### What actually happens?

When my environment is set to _development_ , I am greeted with a fatal Error caused by Monolog\Logger not complying to Psr. 

I checked the composer.lock file and noticed that this is a dependency of Illuminate\Log, which was bumped to version 10.x.x when I updated Acorn  (no other packaged use monolog within this project)

### Steps to reproduce

- Start from a Bedrock(latest), sage(latest), acorn(3) setup
- Update acorn ^3.0 to ^4.0 in composer.json
- Run composer update roots/acorn -W
- Set the application environment to development

### System info

- PHP 8.1 clean install
- redis, opcache, imagick (php extensions)

### Log output

```shell
Fatal error: Declaration of Monolog\Logger::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in /Users/yasser/my_website/vendor/monolog/monolog/src/Monolog/Logger.php on line 681
```

### Please confirm this isn't a support request.

Yes

**Comment by Log1x** [comment]
Please make a thread on [Discourse](https://discourse.roots.io/) with the contents of your `composer.json` for support. This isn't a bug or direct issue with Acorn, but is instead more than likely a conflict with a plugin that isn't wrapping their namespaces. You can read more about this on Acorn's [compatibility docs](https://roots.io/acorn/docs/compatibility/).

**Comment by YasserB94** [comment]
Thank you for your reply Log1x. 

I will take your advice and make a thread on Discourse

**Comment by alaa-alshamy** [comment]
@YasserB94 
Did you find a fix ?

**Comment by tedw** [comment]
Same issue here when upgrading an old site. Any update?

**Comment by Log1x** [comment]
> Same issue here when upgrading an old site. Any update?

No update to be had unfortunately, this isn't something to fix in Acorn. 

You'll have to either refer to the Acorn compatibility page to try some of the workarounds provided for other plugins or contact the plugin author.

**Comment by tedw** [comment]
@Log1x Ah ok, thanks for the follow-up!
