### ISSUE TITLE
Exception after installing Ignition

### ISSUE THREAD

**Issue by oliverhildner** [roots/acorn#389]
### Version

4.3

### What did you expect to happen?

I installed Laravel Ignition as described in the documentation:
`$ composer require spatie/laravel-ignition --dev`
`$ wp acorn optimize:clear`
from a sage-theme folder.
From that moment on, `wp acorn optimize:clear` throws an exception.

### What actually happens?

wp acorn optimize:clear throws an exception:
Declaration of Illuminate\Console\Application::add(Symfony\Component\Console\Command\Command $command) must be compatible with Symfony\Component\Console\Application::add(Symfony\
  Component\Console\Command\Command $command): ?Symfony\Component\Console\Command\Command

### Steps to reproduce

- Install a fresh bedrock project and get it running
- Install Acorn as described in documentation
- Go to the themes-folder and create a sage theme and get it running as in the documentation
- require spatie/laravel/ignition as in the documentation
- run wp acorn optimize:clear

### System info

macOS 14.5 - Docker environment
Php 8.3

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
Steps I followed from the themes directory:

1. `composer create-project roots/sage`
2. `cd sage && yarn && yarn build && wp theme activate sage && wp acorn acorn:install`
3. Select yes on the `acorn:install` prompts
4. `composer require spatie/laravel-ignition --dev`
5. `wp acorn optimize:clear`

Then I added a `{{ $hello }}` to a template:

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/17fd1ba8-7b0f-4d13-a21b-b95496a5eb12">

Feel free to create a topic on Roots Discourse if you need additional help, but there doesn't appear to be any issues with our docs that outline these steps
