### ISSUE TITLE
Routing not working as expected after upgrading from v3.x to v4.x

### ISSUE THREAD

**Issue by bedirhandev** [roots/acorn#393]
### Version

^4.0.0

### What did you expect to happen?

I expect that when I define my routes e.g. `Route::get('dummy', [DummyController::class, 'index']);` in routes/web.php file that the routing should work when I navigate in the browser to e.g. http://localhost/wordpress/dummy and see the correct page.
### What actually happens?

When navigating to http://localhost/wordpress/dummy a 'Page Not Found' message shows up instead of the page that I expect.

### Steps to reproduce

Create a basic route and controller etc and navigate to the uri in the browser.

### System info

Windows 10 pro version 22H2.

### Please confirm this isn't a support request.

Yes

**Comment by bedirhandev** [comment]
Using Acorn v^4.0.0 and WordPress v6.6.1 I noticed that there is something going on in the Bootloader.php (Roots>Acorn>Bootloader.php) in the function registerRequestHandler(..) on line 251.
When commenting this snippet of code $api = parse_url(rest_url(), PHP_URL_PATH); the routing works for me as expected, I don't know if this is a bug.

The error that I get when enabling that line of code is: Error: Call to a member function using_index_permalinks() on null.

That is in file: rest-api.php, line 469 in file wordpress>wp-includes>rest-api.php.

These snippets of code are coming from WordPress and Roots Software Foundation LLC.

https://github.com/roots/acorn/blob/main/LICENSE.md (Roots Software Foundation LLC License)
https://github.com/WordPress/WordPress/blob/master/license.txt (WordPress License)

**Comment by bedirhandev** [comment]
Using Acorn v^4.0.0 and WordPress v6.6.1 I noticed that there is something going on in the Bootloader.php (Roots>Acorn>Bootloader.php) in the function registerRequestHandler(..) on line 251.
When commenting this snippet of code $api = parse_url(rest_url(), PHP_URL_PATH); the routing works for me as expected, I don't know if this is a bug.

The error that I get when enabling that line of code is: Error: Call to a member function using_index_permalinks() on null.

That is in file: rest-api.php, line 469 in file wordpress>wp-includes>rest-api.php.

These snippets of code are coming from WordPress and Roots Software Foundation LLC.

https://github.com/roots/acorn/blob/main/LICENSE.md (Roots Software Foundation LLC License)
https://github.com/WordPress/WordPress/blob/master/license.txt (WordPress License)

**Comment by Log1x** [comment]
Can you try setting https://wordpress.org/documentation/article/customize-permalinks/ to post name?

**Comment by Log1x** [comment]
I looked at the plugin template that got referenced in your issue. A link to that originally would've been helpful.

https://github.com/DeschutesDesignGroupLLC/wordpress-plugin-template/blob/master/yourplugin.php#L41 `EXPERIMENTAL` is typo'd here and was corrected to `EXPERIMENTAL` in v4.

**Comment by bedirhandev** [comment]
@Log1x I really think there is something wrong even after the correction it does not work. Also, I don't use that line at all. Like I mentioned removing line 188: `$api = parse_url(rest_url(), PHP_URL_PATH);` does the fix in file Bootable.php. I am now using the version: ^5.0.0-beta.0. I tried also to change it to post name the permalinks didn't help.

**Comment by bedirhandev** [comment]
> I looked at the plugin template that got referenced in your issue. A link to that originally would've been helpful.
> 
> https://github.com/DeschutesDesignGroupLLC/wordpress-plugin-template/blob/master/yourplugin.php#L41 `EXPERIMENTAL` is typo'd here and was corrected to `EXPERIMENTAL` in v4.

@Log1x I really think there is something wrong even after the correction it does not work. Also, I don't use that line at all. Like I mentioned removing line 188: $api = parse_url(rest_url(), PHP_URL_PATH); does the fix in file Bootable.php. I am now using the version: ^5.0.0-beta.0. I tried also to change it to post name the permalinks didn't help.

**Comment by retlehs** [comment]
The repeated comments aren’t necessary 

What is necessary are **minimal reproduction steps** for this issue 

That means providing all steps **and code** necessary to reproduce this using Acorn itself and not that plugin boilerplate

**Comment by bedirhandev** [comment]
@retlehs I could make a better issue providing more details and also the dirty fix to solve it. For now this is the dirty fix that solved the issue:

There are two places that the code need to change:
1. In this file `vendor\roots\acorn\src\Roots\Acorn\Application\Concerns\Bootable.php` line 188 needs to change to:
`$api = ""; //parse_url(rest_url(), PHP_URL_PATH);`.
2. In this file: `vendor\roots\acorn\src\Roots\Acorn\Application.php` line 133 needs to change to: `$this->{$supportedPaths[$pathType]} = $path;`.

Then the routes are working as expected otherwise it does strange things like prepending and stuff. Like this the plugin works.

My setup is as follows I have a WordPress project and in the path: `C:\xampp\htdocs\wordpress\wp-content\plugins` I have my plugin installed. I am using that template (as referenced) but already did some changes so it is not one-to-one, even with the new configuration e.g. following the steps provided in this link: https://github.com/roots/acorn/pull/370 it fails to work.

**Comment by retlehs** [comment]
I’m locking this since you refuse to provide a minimal reproduction.
