### ISSUE TITLE
laravel_session cookie added to web routes by default

### ISSUE THREAD

**Issue by oxyc** [roots/acorn#395]
### Version

v5

### What did you expect to happen?

No set-cookie headers added for anonymous visitors 

### What actually happens?

laravel_session cookie added to responses

### Steps to reproduce

request any route with web middleware applied

### Please confirm this isn't a support request.

Yes

**Comment by oxyc** [comment]
I know I can turn off the session middleware stuff but would be better if those were opt-in or all page caches will break by default

**Comment by Log1x** [comment]
Are you mainly referring to when on WordPress routes? Otherwise, Laravel always creates a session cookie like that with the session middleware.

**Comment by oxyc** [comment]
When on WordPress routes. Im fine just removing the middleware though if you do want to go with this as the default. But I guess others might find it unexpected too since you cant cache responses with set-cookie and Europeans need to declare the cookie in a policy.

**Comment by Log1x** [comment]
yeah it should definitely be easier to configure and have some saner defaults for wordpress. will figure something out 🙏

**Comment by lagiosdi** [comment]
is there any way to totally disable the session cookie??

**Comment by oxyc** [comment]
```php
Application::configure()
    ->withProviders([
    ])
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->removeFromGroup('web', [
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        ]);
    })
    ->boot();
```

**Comment by lagiosdi** [comment]
@oxyc, thank you very much. But where I write this code? It is not possible to add in vendor folder.
