### ISSUE TITLE
Handing of ValidationExceptions by exception handler

### ISSUE THREAD

**Issue by oskar-koli** [roots/acorn#407]
### Version

Tested only on v4, but looking at the code it seems to be also present in v5.

### What did you expect to happen?

When a ValidationException is thrown from a route, I would expect the request to be redirected to the previous page with an error bag or in the case of a JSON endpoint returning validation errors.

This behavior has been implemented in the Illuminate exception handler's [convertValidationExceptionToResponse method](https://github.com/roots/acorn/blob/b72fd726c02fe5d268eda54e797452bc6db8f09e/src/Illuminate/Foundation/Exceptions/Handler.php#L722). But Acorn's exception handler's [render method](https://github.com/roots/acorn/blob/b72fd726c02fe5d268eda54e797452bc6db8f09e/src/Roots/Acorn/Exceptions/Handler.php#L19) overrides the base class' render method, which results in convertValidationExceptionToResponse never being called for ValidationExceptions. 

Is there some reason for this simplified render method being used, instead of the full implementation which removes support for proper ValidationException handling? This could be fixed by either adding support for ValidationException to the render method override or otherwise maybe even just using the base method, if it doesn't cause any issues. Thoughts? 

### What actually happens?

ValidationExceptions are treated like any other exception and results in the generic error view being rendered.

### Steps to reproduce

1. Throw ValidationException in a route
2. See that the exception does not result in a redirect or correct json response.

### Please confirm this isn't a support request.

Yes

**Comment by Log1x** [comment]
Thanks for the detailed issue!

This is due to the exception handler stuff being implemented prior to any sort of routing.

Care to do a PR?

**Comment by oskar-koli** [comment]
Ok cool, thanks for the quick response! 
Do you think it should be doable just to use the base render method or do some obvious issues come to mind with that?
Will of course test it either way, but just in case you have any thoughts :)

I'll be happy to do a PR, will take a look at it in the coming days 👍

**Comment by Log1x** [comment]
it looks like we'd need to bring in `illuminate/auth` at a glance if we wanted to support the base render method but that should be fine.
