### ISSUE TITLE
If WP-CLI argument '--allow-root' is set, CLI isn't working

### ISSUE THREAD

**Issue by dsturm** [roots/acorn#48]
* [X] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

This might be an edge case, but I thought it should be mentioned: While developing in an Local by Flywheel (3.3.0) environment, the `wp acorn` command(s) resulted in `Command "acorn" is not defined.`. This came from the fact that `wp` is aliased to `wp --allow-root` in this env.

## Steps to reproduce

1. Spin up site in Local by Flywheel
2. Install Sage 10
3. Run `wp acorn`

**Expected behavior:**
Lists all registered CLI commands for acorn.

**Actual behavior:**
Throws error `Command "acorn" is not defined.`.

**Reproduces how often:**
100%

## Versions

"roots/sage": "10.0.0-dev"
"roots/acorn": "dev-master" (58ec37c366f9f45823549149816a6589aa64ba69)

## Additional information

As said, Local by Flywheel sets `alias wp="wp --allow-root"`.

**Comment by Log1x** [comment]
I heavily recommend not using `--allow-root` for obvious reasons, but outside of that– we will need to adjust how we're handling [`argv`](https://github.com/roots/acorn/blob/master/src/Acorn/Bootstrap/Console.php#L27-L53) when registering the CLI.

**Comment by aLANparty** [comment]
Hi. It looks like this issue crept back in with version 1.0.6.  I'm trying to run `wp --allow-root acorn view:cache` as part of a build script, but get the error `Command "acorn" is not defined.`.   I downgraded to 1.0.5 and verified it was working as recently as that version.

**Comment by Jamiewarb** [comment]
I'm running Kinsta's new DevKinsta tool locally, and it seems that currently it's not possible to run `wp` as anything other than root. This makes DevKinsta and Acorn incompatible right now.
