### ISSUE TITLE
View path generated nested component incorrect. 

### ISSUE THREAD

**Issue by mrwokkel** [roots/acorn#72]
* [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [ ] This request isn't a duplicate of an existing issue
* [ ] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When generating a nested component with command `wp acorn make:component Inputs/Button` the view path in the class is incorrect.

    public function render()
    {
        return $this->view('components.button');
    }

Where it should be `components.inputs.button`.

## Steps to reproduce

wp acorn make:component Inputs/Button

**Expected behavior:** [What you expect to happen]

    public function render()
    {
        return $this->view('components.inputs.button');
    }

**Actual behavior:** [What actually happens]

    public function render()
    {
        return $this->view('components.button');
    }

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time :)

## Versions

Version 1.0.1. 

## Additional information

Might be upstream issue

**Comment by QWp6t** [comment]
Thanks for this issue! 👋🏿

This appears to be fixed with our latest updates. I'm not sure which update fixed it, though. But it's currently working on the main branch.
