### ISSUE TITLE
usort returning boolean deprecated

### ISSUE THREAD

**Issue by SergiArias** [roots/acorn#90]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

when running `wp acorn list`:
```
In SummaryCommand.php line 117:
                                                                                                                               
  usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero
```
To solve, just change the usort in SummaryCommand to this:
```php
            usort($commands, function ($a, $b) {
                return $a->getName() > $b->getName() ? 1 : -1;
            });
```

## Steps to reproduce

`wp acorn list`

**Comment by Log1x** [comment]
mind doing a PR?

**Comment by SergiArias** [comment]
Done!
